// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="HLS_accel,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=164,HLS_SYN_DSP=12,HLS_SYN_FF=957,HLS_SYN_LUT=1298}" *)

module HLS_accel (
        ap_clk,
        ap_rst_n,
        INPUT_STREAM_TDATA,
        INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY,
        INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST,
        INPUT_STREAM_TID,
        INPUT_STREAM_TDEST,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST,
        s_axi_CONTROL_BUS_AWVALID,
        s_axi_CONTROL_BUS_AWREADY,
        s_axi_CONTROL_BUS_AWADDR,
        s_axi_CONTROL_BUS_WVALID,
        s_axi_CONTROL_BUS_WREADY,
        s_axi_CONTROL_BUS_WDATA,
        s_axi_CONTROL_BUS_WSTRB,
        s_axi_CONTROL_BUS_ARVALID,
        s_axi_CONTROL_BUS_ARREADY,
        s_axi_CONTROL_BUS_ARADDR,
        s_axi_CONTROL_BUS_RVALID,
        s_axi_CONTROL_BUS_RREADY,
        s_axi_CONTROL_BUS_RDATA,
        s_axi_CONTROL_BUS_RRESP,
        s_axi_CONTROL_BUS_BVALID,
        s_axi_CONTROL_BUS_BREADY,
        s_axi_CONTROL_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_pp0_stage0 = 19'd16;
parameter    ap_ST_fsm_state7 = 19'd32;
parameter    ap_ST_fsm_pp1_stage0 = 19'd64;
parameter    ap_ST_fsm_state10 = 19'd128;
parameter    ap_ST_fsm_pp2_stage0 = 19'd256;
parameter    ap_ST_fsm_state13 = 19'd512;
parameter    ap_ST_fsm_state14 = 19'd1024;
parameter    ap_ST_fsm_state15 = 19'd2048;
parameter    ap_ST_fsm_state16 = 19'd4096;
parameter    ap_ST_fsm_state17 = 19'd8192;
parameter    ap_ST_fsm_state18 = 19'd16384;
parameter    ap_ST_fsm_state19 = 19'd32768;
parameter    ap_ST_fsm_state20 = 19'd65536;
parameter    ap_ST_fsm_pp3_stage0 = 19'd131072;
parameter    ap_ST_fsm_state24 = 19'd262144;
parameter    C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] INPUT_STREAM_TDATA;
input   INPUT_STREAM_TVALID;
output   INPUT_STREAM_TREADY;
input  [3:0] INPUT_STREAM_TKEEP;
input  [3:0] INPUT_STREAM_TSTRB;
input  [3:0] INPUT_STREAM_TUSER;
input  [0:0] INPUT_STREAM_TLAST;
input  [4:0] INPUT_STREAM_TID;
input  [4:0] INPUT_STREAM_TDEST;
output  [31:0] OUTPUT_STREAM_TDATA;
output   OUTPUT_STREAM_TVALID;
input   OUTPUT_STREAM_TREADY;
output  [3:0] OUTPUT_STREAM_TKEEP;
output  [3:0] OUTPUT_STREAM_TSTRB;
output  [3:0] OUTPUT_STREAM_TUSER;
output  [0:0] OUTPUT_STREAM_TLAST;
output  [4:0] OUTPUT_STREAM_TID;
output  [4:0] OUTPUT_STREAM_TDEST;
input   s_axi_CONTROL_BUS_AWVALID;
output   s_axi_CONTROL_BUS_AWREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_AWADDR;
input   s_axi_CONTROL_BUS_WVALID;
output   s_axi_CONTROL_BUS_WREADY;
input  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_WDATA;
input  [C_S_AXI_CONTROL_BUS_WSTRB_WIDTH - 1:0] s_axi_CONTROL_BUS_WSTRB;
input   s_axi_CONTROL_BUS_ARVALID;
output   s_axi_CONTROL_BUS_ARREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_ARADDR;
output   s_axi_CONTROL_BUS_RVALID;
input   s_axi_CONTROL_BUS_RREADY;
output  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_RDATA;
output  [1:0] s_axi_CONTROL_BUS_RRESP;
output   s_axi_CONTROL_BUS_BVALID;
input   s_axi_CONTROL_BUS_BREADY;
output  [1:0] s_axi_CONTROL_BUS_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [31:0] INPUT_STREAM_data_V_0_data_out;
wire    INPUT_STREAM_data_V_0_vld_in;
wire    INPUT_STREAM_data_V_0_vld_out;
wire    INPUT_STREAM_data_V_0_ack_in;
reg    INPUT_STREAM_data_V_0_ack_out;
reg   [31:0] INPUT_STREAM_data_V_0_payload_A;
reg   [31:0] INPUT_STREAM_data_V_0_payload_B;
reg    INPUT_STREAM_data_V_0_sel_rd;
reg    INPUT_STREAM_data_V_0_sel_wr;
wire    INPUT_STREAM_data_V_0_sel;
wire    INPUT_STREAM_data_V_0_load_A;
wire    INPUT_STREAM_data_V_0_load_B;
reg   [1:0] INPUT_STREAM_data_V_0_state;
wire    INPUT_STREAM_data_V_0_state_cmp_full;
wire    INPUT_STREAM_dest_V_0_vld_in;
reg    INPUT_STREAM_dest_V_0_ack_out;
reg   [1:0] INPUT_STREAM_dest_V_0_state;
reg   [31:0] OUTPUT_STREAM_data_V_1_data_out;
reg    OUTPUT_STREAM_data_V_1_vld_in;
wire    OUTPUT_STREAM_data_V_1_vld_out;
wire    OUTPUT_STREAM_data_V_1_ack_in;
wire    OUTPUT_STREAM_data_V_1_ack_out;
reg   [31:0] OUTPUT_STREAM_data_V_1_payload_A;
reg   [31:0] OUTPUT_STREAM_data_V_1_payload_B;
reg    OUTPUT_STREAM_data_V_1_sel_rd;
reg    OUTPUT_STREAM_data_V_1_sel_wr;
wire    OUTPUT_STREAM_data_V_1_sel;
wire    OUTPUT_STREAM_data_V_1_load_A;
wire    OUTPUT_STREAM_data_V_1_load_B;
reg   [1:0] OUTPUT_STREAM_data_V_1_state;
wire    OUTPUT_STREAM_data_V_1_state_cmp_full;
wire   [3:0] OUTPUT_STREAM_keep_V_1_data_out;
reg    OUTPUT_STREAM_keep_V_1_vld_in;
wire    OUTPUT_STREAM_keep_V_1_vld_out;
wire    OUTPUT_STREAM_keep_V_1_ack_in;
wire    OUTPUT_STREAM_keep_V_1_ack_out;
reg    OUTPUT_STREAM_keep_V_1_sel_rd;
wire    OUTPUT_STREAM_keep_V_1_sel;
reg   [1:0] OUTPUT_STREAM_keep_V_1_state;
wire   [3:0] OUTPUT_STREAM_strb_V_1_data_out;
reg    OUTPUT_STREAM_strb_V_1_vld_in;
wire    OUTPUT_STREAM_strb_V_1_vld_out;
wire    OUTPUT_STREAM_strb_V_1_ack_in;
wire    OUTPUT_STREAM_strb_V_1_ack_out;
reg    OUTPUT_STREAM_strb_V_1_sel_rd;
wire    OUTPUT_STREAM_strb_V_1_sel;
reg   [1:0] OUTPUT_STREAM_strb_V_1_state;
wire   [3:0] OUTPUT_STREAM_user_V_1_data_out;
reg    OUTPUT_STREAM_user_V_1_vld_in;
wire    OUTPUT_STREAM_user_V_1_vld_out;
wire    OUTPUT_STREAM_user_V_1_ack_in;
wire    OUTPUT_STREAM_user_V_1_ack_out;
reg    OUTPUT_STREAM_user_V_1_sel_rd;
wire    OUTPUT_STREAM_user_V_1_sel;
reg   [1:0] OUTPUT_STREAM_user_V_1_state;
reg   [0:0] OUTPUT_STREAM_last_V_1_data_out;
reg    OUTPUT_STREAM_last_V_1_vld_in;
wire    OUTPUT_STREAM_last_V_1_vld_out;
wire    OUTPUT_STREAM_last_V_1_ack_in;
wire    OUTPUT_STREAM_last_V_1_ack_out;
reg   [0:0] OUTPUT_STREAM_last_V_1_payload_A;
reg   [0:0] OUTPUT_STREAM_last_V_1_payload_B;
reg    OUTPUT_STREAM_last_V_1_sel_rd;
reg    OUTPUT_STREAM_last_V_1_sel_wr;
wire    OUTPUT_STREAM_last_V_1_sel;
wire    OUTPUT_STREAM_last_V_1_load_A;
wire    OUTPUT_STREAM_last_V_1_load_B;
reg   [1:0] OUTPUT_STREAM_last_V_1_state;
wire    OUTPUT_STREAM_last_V_1_state_cmp_full;
wire   [4:0] OUTPUT_STREAM_id_V_1_data_out;
reg    OUTPUT_STREAM_id_V_1_vld_in;
wire    OUTPUT_STREAM_id_V_1_vld_out;
wire    OUTPUT_STREAM_id_V_1_ack_in;
wire    OUTPUT_STREAM_id_V_1_ack_out;
reg    OUTPUT_STREAM_id_V_1_sel_rd;
wire    OUTPUT_STREAM_id_V_1_sel;
reg   [1:0] OUTPUT_STREAM_id_V_1_state;
wire   [4:0] OUTPUT_STREAM_dest_V_1_data_out;
reg    OUTPUT_STREAM_dest_V_1_vld_in;
wire    OUTPUT_STREAM_dest_V_1_vld_out;
wire    OUTPUT_STREAM_dest_V_1_ack_in;
wire    OUTPUT_STREAM_dest_V_1_ack_out;
reg    OUTPUT_STREAM_dest_V_1_sel_rd;
wire    OUTPUT_STREAM_dest_V_1_sel;
reg   [1:0] OUTPUT_STREAM_dest_V_1_state;
reg    INPUT_STREAM_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond3_i_reg_531;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] exitcond2_i_reg_540;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage0;
reg   [0:0] exitcond1_i_reg_549;
reg    OUTPUT_STREAM_TDATA_blk_n;
wire    ap_CS_fsm_pp3_stage0;
reg    ap_enable_reg_pp3_iter1;
wire    ap_block_pp3_stage0;
reg   [0:0] exitcond_i_reg_648;
reg    ap_enable_reg_pp3_iter2;
reg   [0:0] ap_reg_pp3_iter1_exitcond_i_reg_648;
reg   [10:0] i_0_i_reg_255;
reg   [13:0] i1_0_i_reg_267;
reg   [14:0] i2_0_i_reg_279;
reg   [14:0] i3_0_i_reg_324;
reg   [31:0] M_reg_513;
reg  signed [31:0] N_reg_518;
reg  signed [31:0] K_reg_525;
wire   [0:0] exitcond3_i_fu_342_p2;
wire    ap_block_state5_pp0_stage0_iter0;
reg    ap_block_state6_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [10:0] i_fu_348_p2;
reg   [10:0] i_reg_535;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] exitcond2_i_fu_359_p2;
wire    ap_block_state8_pp1_stage0_iter0;
reg    ap_block_state9_pp1_stage0_iter1;
reg    ap_block_pp1_stage0_11001;
wire   [13:0] i_1_fu_365_p2;
reg   [13:0] i_1_reg_544;
reg    ap_enable_reg_pp1_iter0;
wire   [0:0] exitcond1_i_fu_376_p2;
wire    ap_block_state11_pp2_stage0_iter0;
reg    ap_block_state12_pp2_stage0_iter1;
reg    ap_block_pp2_stage0_11001;
wire   [14:0] i_2_fu_382_p2;
reg   [14:0] i_2_reg_553;
reg    ap_enable_reg_pp2_iter0;
wire   [0:0] tmp_3_fu_397_p2;
wire    ap_CS_fsm_state14;
wire   [30:0] i_3_fu_402_p2;
reg   [30:0] i_3_reg_562;
wire   [31:0] tmp_7_fu_408_p2;
reg   [31:0] tmp_7_reg_567;
wire   [31:0] tmp_9_fu_413_p2;
reg   [31:0] tmp_9_reg_572;
wire   [31:0] k_0_i_i_cast_fu_418_p1;
reg   [31:0] k_0_i_i_cast_reg_577;
wire    ap_CS_fsm_state15;
wire   [30:0] k_fu_427_p2;
reg   [30:0] k_reg_585;
wire   [0:0] tmp_10_fu_422_p2;
wire   [31:0] a_q0;
reg  signed [31:0] A_PART_reg_595;
wire    ap_CS_fsm_state16;
wire   [31:0] tmp_14_fu_443_p2;
reg   [31:0] tmp_14_reg_600;
wire   [30:0] j_fu_456_p2;
reg   [30:0] j_reg_608;
wire    ap_CS_fsm_state17;
wire   [31:0] tmp_17_fu_462_p2;
reg   [31:0] tmp_17_reg_613;
wire   [0:0] tmp_16_fu_451_p2;
wire  signed [63:0] tmp_18_fu_477_p1;
reg  signed [63:0] tmp_18_reg_623;
wire    ap_CS_fsm_state18;
wire   [31:0] b_q0;
reg  signed [31:0] b_load_reg_633;
wire   [31:0] c_q0;
reg   [31:0] c_load_reg_638;
wire    ap_CS_fsm_state19;
wire   [31:0] tmp_21_fu_481_p2;
reg   [31:0] tmp_21_reg_643;
wire   [0:0] exitcond_i_fu_490_p2;
wire    ap_block_state21_pp3_stage0_iter0;
wire    ap_block_state22_pp3_stage0_iter1;
reg    ap_block_state22_io;
wire    ap_block_state23_pp3_stage0_iter2;
reg    ap_block_state23_io;
reg    ap_block_pp3_stage0_11001;
wire   [14:0] i_4_fu_496_p2;
reg    ap_enable_reg_pp3_iter0;
wire   [0:0] last_assign_fu_507_p2;
reg   [0:0] last_assign_reg_662;
wire   [31:0] out_q0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state5;
wire    ap_CS_fsm_state7;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state8;
wire    ap_CS_fsm_state10;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state11;
reg    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_exit_iter0_state21;
reg   [10:0] a_address0;
reg    a_ce0;
reg    a_we0;
reg   [13:0] b_address0;
reg    b_ce0;
reg    b_we0;
reg   [14:0] c_address0;
reg    c_ce0;
reg    c_we0;
reg   [14:0] out_address0;
reg    out_ce0;
reg    out_we0;
wire   [31:0] out_d0;
reg   [10:0] ap_phi_mux_i_0_i_phi_fu_259_p4;
reg   [13:0] ap_phi_mux_i1_0_i_phi_fu_271_p4;
reg   [14:0] ap_phi_mux_i2_0_i_phi_fu_283_p4;
reg   [30:0] i_0_i_i_reg_291;
wire    ap_CS_fsm_state13;
reg   [30:0] k_0_i_i_reg_302;
reg   [30:0] j_0_i_i_reg_313;
wire    ap_CS_fsm_state20;
wire   [63:0] tmp_2_fu_354_p1;
wire   [63:0] tmp_6_fu_371_p1;
wire   [63:0] tmp_s_fu_388_p1;
wire  signed [63:0] tmp_13_fu_438_p1;
wire  signed [63:0] tmp_20_fu_472_p1;
wire   [63:0] tmp_15_fu_502_p1;
wire    ap_block_pp3_stage0_01001;
wire   [31:0] i_0_i_i_cast_fu_393_p1;
wire   [30:0] tmp_7_fu_408_p1;
wire   [30:0] tmp_9_fu_413_p1;
wire   [31:0] tmp_12_fu_433_p2;
wire   [30:0] tmp_14_fu_443_p1;
wire   [31:0] j_0_i_i_cast_fu_447_p1;
wire   [31:0] tmp_19_fu_467_p2;
wire    ap_CS_fsm_state24;
reg    ap_block_state24;
reg   [18:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;

// power-on initialization
initial begin
#0 ap_CS_fsm = 19'd1;
#0 INPUT_STREAM_data_V_0_sel_rd = 1'b0;
#0 INPUT_STREAM_data_V_0_sel_wr = 1'b0;
#0 INPUT_STREAM_data_V_0_state = 2'd0;
#0 INPUT_STREAM_dest_V_0_state = 2'd0;
#0 OUTPUT_STREAM_data_V_1_sel_rd = 1'b0;
#0 OUTPUT_STREAM_data_V_1_sel_wr = 1'b0;
#0 OUTPUT_STREAM_data_V_1_state = 2'd0;
#0 OUTPUT_STREAM_keep_V_1_sel_rd = 1'b0;
#0 OUTPUT_STREAM_keep_V_1_state = 2'd0;
#0 OUTPUT_STREAM_strb_V_1_sel_rd = 1'b0;
#0 OUTPUT_STREAM_strb_V_1_state = 2'd0;
#0 OUTPUT_STREAM_user_V_1_sel_rd = 1'b0;
#0 OUTPUT_STREAM_user_V_1_state = 2'd0;
#0 OUTPUT_STREAM_last_V_1_sel_rd = 1'b0;
#0 OUTPUT_STREAM_last_V_1_sel_wr = 1'b0;
#0 OUTPUT_STREAM_last_V_1_state = 2'd0;
#0 OUTPUT_STREAM_id_V_1_sel_rd = 1'b0;
#0 OUTPUT_STREAM_id_V_1_state = 2'd0;
#0 OUTPUT_STREAM_dest_V_1_sel_rd = 1'b0;
#0 OUTPUT_STREAM_dest_V_1_state = 2'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
end

HLS_accel_CONTROL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_BUS_DATA_WIDTH ))
HLS_accel_CONTROL_BUS_s_axi_U(
    .AWVALID(s_axi_CONTROL_BUS_AWVALID),
    .AWREADY(s_axi_CONTROL_BUS_AWREADY),
    .AWADDR(s_axi_CONTROL_BUS_AWADDR),
    .WVALID(s_axi_CONTROL_BUS_WVALID),
    .WREADY(s_axi_CONTROL_BUS_WREADY),
    .WDATA(s_axi_CONTROL_BUS_WDATA),
    .WSTRB(s_axi_CONTROL_BUS_WSTRB),
    .ARVALID(s_axi_CONTROL_BUS_ARVALID),
    .ARREADY(s_axi_CONTROL_BUS_ARREADY),
    .ARADDR(s_axi_CONTROL_BUS_ARADDR),
    .RVALID(s_axi_CONTROL_BUS_RVALID),
    .RREADY(s_axi_CONTROL_BUS_RREADY),
    .RDATA(s_axi_CONTROL_BUS_RDATA),
    .RRESP(s_axi_CONTROL_BUS_RRESP),
    .BVALID(s_axi_CONTROL_BUS_BVALID),
    .BREADY(s_axi_CONTROL_BUS_BREADY),
    .BRESP(s_axi_CONTROL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

HLS_accel_a #(
    .DataWidth( 32 ),
    .AddressRange( 1350 ),
    .AddressWidth( 11 ))
a_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(a_address0),
    .ce0(a_ce0),
    .we0(a_we0),
    .d0(INPUT_STREAM_data_V_0_data_out),
    .q0(a_q0)
);

HLS_accel_b #(
    .DataWidth( 32 ),
    .AddressRange( 13500 ),
    .AddressWidth( 14 ))
b_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(b_address0),
    .ce0(b_ce0),
    .we0(b_we0),
    .d0(INPUT_STREAM_data_V_0_data_out),
    .q0(b_q0)
);

HLS_accel_c #(
    .DataWidth( 32 ),
    .AddressRange( 25000 ),
    .AddressWidth( 15 ))
c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(c_address0),
    .ce0(c_ce0),
    .we0(c_we0),
    .d0(INPUT_STREAM_data_V_0_data_out),
    .q0(c_q0)
);

HLS_accel_c #(
    .DataWidth( 32 ),
    .AddressRange( 25000 ),
    .AddressWidth( 15 ))
out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(out_address0),
    .ce0(out_ce0),
    .we0(out_we0),
    .d0(out_d0),
    .q0(out_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        INPUT_STREAM_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == INPUT_STREAM_data_V_0_ack_out) & (1'b1 == INPUT_STREAM_data_V_0_vld_out))) begin
            INPUT_STREAM_data_V_0_sel_rd <= ~INPUT_STREAM_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        INPUT_STREAM_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == INPUT_STREAM_data_V_0_ack_in) & (1'b1 == INPUT_STREAM_data_V_0_vld_in))) begin
            INPUT_STREAM_data_V_0_sel_wr <= ~INPUT_STREAM_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        INPUT_STREAM_data_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == INPUT_STREAM_data_V_0_state) & (1'b0 == INPUT_STREAM_data_V_0_vld_in)) | ((2'd3 == INPUT_STREAM_data_V_0_state) & (1'b0 == INPUT_STREAM_data_V_0_vld_in) & (1'b1 == INPUT_STREAM_data_V_0_ack_out)))) begin
            INPUT_STREAM_data_V_0_state <= 2'd2;
        end else if ((((2'd1 == INPUT_STREAM_data_V_0_state) & (1'b0 == INPUT_STREAM_data_V_0_ack_out)) | ((2'd3 == INPUT_STREAM_data_V_0_state) & (1'b0 == INPUT_STREAM_data_V_0_ack_out) & (1'b1 == INPUT_STREAM_data_V_0_vld_in)))) begin
            INPUT_STREAM_data_V_0_state <= 2'd1;
        end else if (((~((1'b0 == INPUT_STREAM_data_V_0_vld_in) & (1'b1 == INPUT_STREAM_data_V_0_ack_out)) & ~((1'b0 == INPUT_STREAM_data_V_0_ack_out) & (1'b1 == INPUT_STREAM_data_V_0_vld_in)) & (2'd3 == INPUT_STREAM_data_V_0_state)) | ((2'd1 == INPUT_STREAM_data_V_0_state) & (1'b1 == INPUT_STREAM_data_V_0_ack_out)) | ((2'd2 == INPUT_STREAM_data_V_0_state) & (1'b1 == INPUT_STREAM_data_V_0_vld_in)))) begin
            INPUT_STREAM_data_V_0_state <= 2'd3;
        end else begin
            INPUT_STREAM_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        INPUT_STREAM_dest_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == INPUT_STREAM_dest_V_0_state) & (1'b0 == INPUT_STREAM_dest_V_0_vld_in)) | ((2'd3 == INPUT_STREAM_dest_V_0_state) & (1'b0 == INPUT_STREAM_dest_V_0_vld_in) & (1'b1 == INPUT_STREAM_dest_V_0_ack_out)))) begin
            INPUT_STREAM_dest_V_0_state <= 2'd2;
        end else if ((((2'd1 == INPUT_STREAM_dest_V_0_state) & (1'b0 == INPUT_STREAM_dest_V_0_ack_out)) | ((2'd3 == INPUT_STREAM_dest_V_0_state) & (1'b0 == INPUT_STREAM_dest_V_0_ack_out) & (1'b1 == INPUT_STREAM_dest_V_0_vld_in)))) begin
            INPUT_STREAM_dest_V_0_state <= 2'd1;
        end else if (((~((1'b0 == INPUT_STREAM_dest_V_0_vld_in) & (1'b1 == INPUT_STREAM_dest_V_0_ack_out)) & ~((1'b0 == INPUT_STREAM_dest_V_0_ack_out) & (1'b1 == INPUT_STREAM_dest_V_0_vld_in)) & (2'd3 == INPUT_STREAM_dest_V_0_state)) | ((2'd1 == INPUT_STREAM_dest_V_0_state) & (1'b1 == INPUT_STREAM_dest_V_0_ack_out)) | ((2'd2 == INPUT_STREAM_dest_V_0_state) & (1'b1 == INPUT_STREAM_dest_V_0_vld_in)))) begin
            INPUT_STREAM_dest_V_0_state <= 2'd3;
        end else begin
            INPUT_STREAM_dest_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == OUTPUT_STREAM_data_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_data_V_1_vld_out))) begin
            OUTPUT_STREAM_data_V_1_sel_rd <= ~OUTPUT_STREAM_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == OUTPUT_STREAM_data_V_1_ack_in) & (1'b1 == OUTPUT_STREAM_data_V_1_vld_in))) begin
            OUTPUT_STREAM_data_V_1_sel_wr <= ~OUTPUT_STREAM_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_data_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == OUTPUT_STREAM_data_V_1_state) & (1'b0 == OUTPUT_STREAM_data_V_1_vld_in)) | ((2'd3 == OUTPUT_STREAM_data_V_1_state) & (1'b0 == OUTPUT_STREAM_data_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_data_V_1_ack_out)))) begin
            OUTPUT_STREAM_data_V_1_state <= 2'd2;
        end else if ((((2'd1 == OUTPUT_STREAM_data_V_1_state) & (1'b0 == OUTPUT_STREAM_data_V_1_ack_out)) | ((2'd3 == OUTPUT_STREAM_data_V_1_state) & (1'b0 == OUTPUT_STREAM_data_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_data_V_1_vld_in)))) begin
            OUTPUT_STREAM_data_V_1_state <= 2'd1;
        end else if (((~((1'b0 == OUTPUT_STREAM_data_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_data_V_1_ack_out)) & ~((1'b0 == OUTPUT_STREAM_data_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_data_V_1_vld_in)) & (2'd3 == OUTPUT_STREAM_data_V_1_state)) | ((2'd1 == OUTPUT_STREAM_data_V_1_state) & (1'b1 == OUTPUT_STREAM_data_V_1_ack_out)) | ((2'd2 == OUTPUT_STREAM_data_V_1_state) & (1'b1 == OUTPUT_STREAM_data_V_1_vld_in)))) begin
            OUTPUT_STREAM_data_V_1_state <= 2'd3;
        end else begin
            OUTPUT_STREAM_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_dest_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == OUTPUT_STREAM_dest_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_dest_V_1_vld_out))) begin
            OUTPUT_STREAM_dest_V_1_sel_rd <= ~OUTPUT_STREAM_dest_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_dest_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == OUTPUT_STREAM_dest_V_1_state) & (1'b0 == OUTPUT_STREAM_dest_V_1_vld_in)) | ((2'd3 == OUTPUT_STREAM_dest_V_1_state) & (1'b0 == OUTPUT_STREAM_dest_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_dest_V_1_ack_out)))) begin
            OUTPUT_STREAM_dest_V_1_state <= 2'd2;
        end else if ((((2'd1 == OUTPUT_STREAM_dest_V_1_state) & (1'b0 == OUTPUT_STREAM_dest_V_1_ack_out)) | ((2'd3 == OUTPUT_STREAM_dest_V_1_state) & (1'b0 == OUTPUT_STREAM_dest_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_dest_V_1_vld_in)))) begin
            OUTPUT_STREAM_dest_V_1_state <= 2'd1;
        end else if (((~((1'b0 == OUTPUT_STREAM_dest_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_dest_V_1_ack_out)) & ~((1'b0 == OUTPUT_STREAM_dest_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_dest_V_1_vld_in)) & (2'd3 == OUTPUT_STREAM_dest_V_1_state)) | ((2'd1 == OUTPUT_STREAM_dest_V_1_state) & (1'b1 == OUTPUT_STREAM_dest_V_1_ack_out)) | ((2'd2 == OUTPUT_STREAM_dest_V_1_state) & (1'b1 == OUTPUT_STREAM_dest_V_1_vld_in)))) begin
            OUTPUT_STREAM_dest_V_1_state <= 2'd3;
        end else begin
            OUTPUT_STREAM_dest_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_id_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == OUTPUT_STREAM_id_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_id_V_1_vld_out))) begin
            OUTPUT_STREAM_id_V_1_sel_rd <= ~OUTPUT_STREAM_id_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_id_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == OUTPUT_STREAM_id_V_1_state) & (1'b0 == OUTPUT_STREAM_id_V_1_vld_in)) | ((2'd3 == OUTPUT_STREAM_id_V_1_state) & (1'b0 == OUTPUT_STREAM_id_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_id_V_1_ack_out)))) begin
            OUTPUT_STREAM_id_V_1_state <= 2'd2;
        end else if ((((2'd1 == OUTPUT_STREAM_id_V_1_state) & (1'b0 == OUTPUT_STREAM_id_V_1_ack_out)) | ((2'd3 == OUTPUT_STREAM_id_V_1_state) & (1'b0 == OUTPUT_STREAM_id_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_id_V_1_vld_in)))) begin
            OUTPUT_STREAM_id_V_1_state <= 2'd1;
        end else if (((~((1'b0 == OUTPUT_STREAM_id_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_id_V_1_ack_out)) & ~((1'b0 == OUTPUT_STREAM_id_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_id_V_1_vld_in)) & (2'd3 == OUTPUT_STREAM_id_V_1_state)) | ((2'd1 == OUTPUT_STREAM_id_V_1_state) & (1'b1 == OUTPUT_STREAM_id_V_1_ack_out)) | ((2'd2 == OUTPUT_STREAM_id_V_1_state) & (1'b1 == OUTPUT_STREAM_id_V_1_vld_in)))) begin
            OUTPUT_STREAM_id_V_1_state <= 2'd3;
        end else begin
            OUTPUT_STREAM_id_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == OUTPUT_STREAM_keep_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_keep_V_1_vld_out))) begin
            OUTPUT_STREAM_keep_V_1_sel_rd <= ~OUTPUT_STREAM_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_keep_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == OUTPUT_STREAM_keep_V_1_state) & (1'b0 == OUTPUT_STREAM_keep_V_1_vld_in)) | ((2'd3 == OUTPUT_STREAM_keep_V_1_state) & (1'b0 == OUTPUT_STREAM_keep_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_keep_V_1_ack_out)))) begin
            OUTPUT_STREAM_keep_V_1_state <= 2'd2;
        end else if ((((2'd1 == OUTPUT_STREAM_keep_V_1_state) & (1'b0 == OUTPUT_STREAM_keep_V_1_ack_out)) | ((2'd3 == OUTPUT_STREAM_keep_V_1_state) & (1'b0 == OUTPUT_STREAM_keep_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_keep_V_1_vld_in)))) begin
            OUTPUT_STREAM_keep_V_1_state <= 2'd1;
        end else if (((~((1'b0 == OUTPUT_STREAM_keep_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_keep_V_1_ack_out)) & ~((1'b0 == OUTPUT_STREAM_keep_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_keep_V_1_vld_in)) & (2'd3 == OUTPUT_STREAM_keep_V_1_state)) | ((2'd1 == OUTPUT_STREAM_keep_V_1_state) & (1'b1 == OUTPUT_STREAM_keep_V_1_ack_out)) | ((2'd2 == OUTPUT_STREAM_keep_V_1_state) & (1'b1 == OUTPUT_STREAM_keep_V_1_vld_in)))) begin
            OUTPUT_STREAM_keep_V_1_state <= 2'd3;
        end else begin
            OUTPUT_STREAM_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == OUTPUT_STREAM_last_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_last_V_1_vld_out))) begin
            OUTPUT_STREAM_last_V_1_sel_rd <= ~OUTPUT_STREAM_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == OUTPUT_STREAM_last_V_1_ack_in) & (1'b1 == OUTPUT_STREAM_last_V_1_vld_in))) begin
            OUTPUT_STREAM_last_V_1_sel_wr <= ~OUTPUT_STREAM_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_last_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == OUTPUT_STREAM_last_V_1_state) & (1'b0 == OUTPUT_STREAM_last_V_1_vld_in)) | ((2'd3 == OUTPUT_STREAM_last_V_1_state) & (1'b0 == OUTPUT_STREAM_last_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_last_V_1_ack_out)))) begin
            OUTPUT_STREAM_last_V_1_state <= 2'd2;
        end else if ((((2'd1 == OUTPUT_STREAM_last_V_1_state) & (1'b0 == OUTPUT_STREAM_last_V_1_ack_out)) | ((2'd3 == OUTPUT_STREAM_last_V_1_state) & (1'b0 == OUTPUT_STREAM_last_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_last_V_1_vld_in)))) begin
            OUTPUT_STREAM_last_V_1_state <= 2'd1;
        end else if (((~((1'b0 == OUTPUT_STREAM_last_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_last_V_1_ack_out)) & ~((1'b0 == OUTPUT_STREAM_last_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_last_V_1_vld_in)) & (2'd3 == OUTPUT_STREAM_last_V_1_state)) | ((2'd1 == OUTPUT_STREAM_last_V_1_state) & (1'b1 == OUTPUT_STREAM_last_V_1_ack_out)) | ((2'd2 == OUTPUT_STREAM_last_V_1_state) & (1'b1 == OUTPUT_STREAM_last_V_1_vld_in)))) begin
            OUTPUT_STREAM_last_V_1_state <= 2'd3;
        end else begin
            OUTPUT_STREAM_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == OUTPUT_STREAM_strb_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_strb_V_1_vld_out))) begin
            OUTPUT_STREAM_strb_V_1_sel_rd <= ~OUTPUT_STREAM_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_strb_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == OUTPUT_STREAM_strb_V_1_state) & (1'b0 == OUTPUT_STREAM_strb_V_1_vld_in)) | ((2'd3 == OUTPUT_STREAM_strb_V_1_state) & (1'b0 == OUTPUT_STREAM_strb_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_strb_V_1_ack_out)))) begin
            OUTPUT_STREAM_strb_V_1_state <= 2'd2;
        end else if ((((2'd1 == OUTPUT_STREAM_strb_V_1_state) & (1'b0 == OUTPUT_STREAM_strb_V_1_ack_out)) | ((2'd3 == OUTPUT_STREAM_strb_V_1_state) & (1'b0 == OUTPUT_STREAM_strb_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_strb_V_1_vld_in)))) begin
            OUTPUT_STREAM_strb_V_1_state <= 2'd1;
        end else if (((~((1'b0 == OUTPUT_STREAM_strb_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_strb_V_1_ack_out)) & ~((1'b0 == OUTPUT_STREAM_strb_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_strb_V_1_vld_in)) & (2'd3 == OUTPUT_STREAM_strb_V_1_state)) | ((2'd1 == OUTPUT_STREAM_strb_V_1_state) & (1'b1 == OUTPUT_STREAM_strb_V_1_ack_out)) | ((2'd2 == OUTPUT_STREAM_strb_V_1_state) & (1'b1 == OUTPUT_STREAM_strb_V_1_vld_in)))) begin
            OUTPUT_STREAM_strb_V_1_state <= 2'd3;
        end else begin
            OUTPUT_STREAM_strb_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_user_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == OUTPUT_STREAM_user_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_user_V_1_vld_out))) begin
            OUTPUT_STREAM_user_V_1_sel_rd <= ~OUTPUT_STREAM_user_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        OUTPUT_STREAM_user_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == OUTPUT_STREAM_user_V_1_state) & (1'b0 == OUTPUT_STREAM_user_V_1_vld_in)) | ((2'd3 == OUTPUT_STREAM_user_V_1_state) & (1'b0 == OUTPUT_STREAM_user_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_user_V_1_ack_out)))) begin
            OUTPUT_STREAM_user_V_1_state <= 2'd2;
        end else if ((((2'd1 == OUTPUT_STREAM_user_V_1_state) & (1'b0 == OUTPUT_STREAM_user_V_1_ack_out)) | ((2'd3 == OUTPUT_STREAM_user_V_1_state) & (1'b0 == OUTPUT_STREAM_user_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_user_V_1_vld_in)))) begin
            OUTPUT_STREAM_user_V_1_state <= 2'd1;
        end else if (((~((1'b0 == OUTPUT_STREAM_user_V_1_vld_in) & (1'b1 == OUTPUT_STREAM_user_V_1_ack_out)) & ~((1'b0 == OUTPUT_STREAM_user_V_1_ack_out) & (1'b1 == OUTPUT_STREAM_user_V_1_vld_in)) & (2'd3 == OUTPUT_STREAM_user_V_1_state)) | ((2'd1 == OUTPUT_STREAM_user_V_1_state) & (1'b1 == OUTPUT_STREAM_user_V_1_ack_out)) | ((2'd2 == OUTPUT_STREAM_user_V_1_state) & (1'b1 == OUTPUT_STREAM_user_V_1_vld_in)))) begin
            OUTPUT_STREAM_user_V_1_state <= 2'd3;
        end else begin
            OUTPUT_STREAM_user_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state5) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state5) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state5);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_condition_pp1_exit_iter0_state8) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp1_exit_iter0_state8) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state8);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_condition_pp2_exit_iter0_state11) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp2_exit_iter0_state11) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
            ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state11);
        end else if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b1 == ap_condition_pp3_exit_iter0_state21) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if (((tmp_3_fu_397_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp3_exit_iter0_state21)) begin
                ap_enable_reg_pp3_iter1 <= (1'b1 ^ ap_condition_pp3_exit_iter0_state21);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
        end else if (((tmp_3_fu_397_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
            ap_enable_reg_pp3_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i1_0_i_reg_267 <= 14'd0;
    end else if (((exitcond2_i_reg_540 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        i1_0_i_reg_267 <= i_1_reg_544;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        i2_0_i_reg_279 <= 15'd0;
    end else if (((exitcond1_i_reg_549 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        i2_0_i_reg_279 <= i_2_reg_553;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_397_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        i3_0_i_reg_324 <= 15'd0;
    end else if (((exitcond_i_fu_490_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        i3_0_i_reg_324 <= i_4_fu_496_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        i_0_i_i_reg_291 <= 31'd0;
    end else if (((tmp_10_fu_422_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
        i_0_i_i_reg_291 <= i_3_reg_562;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond3_i_reg_531 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_0_i_reg_255 <= i_reg_535;
    end else if (((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state4))) begin
        i_0_i_reg_255 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        j_0_i_i_reg_313 <= j_reg_608;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        j_0_i_i_reg_313 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_16_fu_451_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        k_0_i_i_reg_302 <= k_reg_585;
    end else if (((tmp_3_fu_397_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        k_0_i_i_reg_302 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        A_PART_reg_595 <= a_q0;
        tmp_14_reg_600 <= tmp_14_fu_443_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == INPUT_STREAM_data_V_0_load_A)) begin
        INPUT_STREAM_data_V_0_payload_A <= INPUT_STREAM_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == INPUT_STREAM_data_V_0_load_B)) begin
        INPUT_STREAM_data_V_0_payload_B <= INPUT_STREAM_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state4))) begin
        K_reg_525 <= INPUT_STREAM_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2))) begin
        M_reg_513 <= INPUT_STREAM_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state3))) begin
        N_reg_518 <= INPUT_STREAM_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == OUTPUT_STREAM_data_V_1_load_A)) begin
        OUTPUT_STREAM_data_V_1_payload_A <= out_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == OUTPUT_STREAM_data_V_1_load_B)) begin
        OUTPUT_STREAM_data_V_1_payload_B <= out_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == OUTPUT_STREAM_last_V_1_load_A)) begin
        OUTPUT_STREAM_last_V_1_payload_A <= last_assign_reg_662;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == OUTPUT_STREAM_last_V_1_load_B)) begin
        OUTPUT_STREAM_last_V_1_payload_B <= last_assign_reg_662;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        ap_reg_pp3_iter1_exitcond_i_reg_648 <= exitcond_i_reg_648;
        exitcond_i_reg_648 <= exitcond_i_fu_490_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        b_load_reg_633 <= b_q0;
        tmp_18_reg_623 <= tmp_18_fu_477_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        c_load_reg_638 <= c_q0;
        tmp_21_reg_643 <= tmp_21_fu_481_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        exitcond1_i_reg_549 <= exitcond1_i_fu_376_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        exitcond2_i_reg_540 <= exitcond2_i_fu_359_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond3_i_reg_531 <= exitcond3_i_fu_342_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        i_1_reg_544 <= i_1_fu_365_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        i_2_reg_553 <= i_2_fu_382_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        i_3_reg_562 <= i_3_fu_402_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        i_reg_535 <= i_fu_348_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        j_reg_608 <= j_fu_456_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        k_0_i_i_cast_reg_577[30 : 0] <= k_0_i_i_cast_fu_418_p1[30 : 0];
        k_reg_585 <= k_fu_427_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_490_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        last_assign_reg_662 <= last_assign_fu_507_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_16_fu_451_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        tmp_17_reg_613 <= tmp_17_fu_462_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_397_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        tmp_7_reg_567 <= tmp_7_fu_408_p2;
        tmp_9_reg_572 <= tmp_9_fu_413_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_pp2_stage0) & (exitcond1_i_reg_549 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage0) & (exitcond2_i_reg_540 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (exitcond3_i_reg_531 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        INPUT_STREAM_TDATA_blk_n = INPUT_STREAM_data_V_0_state[1'd0];
    end else begin
        INPUT_STREAM_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((exitcond1_i_reg_549 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | ((exitcond2_i_reg_540 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b0 == ap_block_pp0_stage0_11001) & (exitcond3_i_reg_531 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2)))) begin
        INPUT_STREAM_data_V_0_ack_out = 1'b1;
    end else begin
        INPUT_STREAM_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == INPUT_STREAM_data_V_0_sel)) begin
        INPUT_STREAM_data_V_0_data_out = INPUT_STREAM_data_V_0_payload_B;
    end else begin
        INPUT_STREAM_data_V_0_data_out = INPUT_STREAM_data_V_0_payload_A;
    end
end

always @ (*) begin
    if ((((exitcond1_i_reg_549 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | ((exitcond2_i_reg_540 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b0 == ap_block_pp0_stage0_11001) & (exitcond3_i_reg_531 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2)))) begin
        INPUT_STREAM_dest_V_0_ack_out = 1'b1;
    end else begin
        INPUT_STREAM_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp3_stage0) & (ap_reg_pp3_iter1_exitcond_i_reg_648 == 1'd0) & (ap_enable_reg_pp3_iter2 == 1'b1)) | ((1'b0 == ap_block_pp3_stage0) & (exitcond_i_reg_648 == 1'd0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        OUTPUT_STREAM_TDATA_blk_n = OUTPUT_STREAM_data_V_1_state[1'd1];
    end else begin
        OUTPUT_STREAM_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == OUTPUT_STREAM_data_V_1_sel)) begin
        OUTPUT_STREAM_data_V_1_data_out = OUTPUT_STREAM_data_V_1_payload_B;
    end else begin
        OUTPUT_STREAM_data_V_1_data_out = OUTPUT_STREAM_data_V_1_payload_A;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_648 == 1'd0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        OUTPUT_STREAM_data_V_1_vld_in = 1'b1;
    end else begin
        OUTPUT_STREAM_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_648 == 1'd0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        OUTPUT_STREAM_dest_V_1_vld_in = 1'b1;
    end else begin
        OUTPUT_STREAM_dest_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_648 == 1'd0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        OUTPUT_STREAM_id_V_1_vld_in = 1'b1;
    end else begin
        OUTPUT_STREAM_id_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_648 == 1'd0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        OUTPUT_STREAM_keep_V_1_vld_in = 1'b1;
    end else begin
        OUTPUT_STREAM_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == OUTPUT_STREAM_last_V_1_sel)) begin
        OUTPUT_STREAM_last_V_1_data_out = OUTPUT_STREAM_last_V_1_payload_B;
    end else begin
        OUTPUT_STREAM_last_V_1_data_out = OUTPUT_STREAM_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_648 == 1'd0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        OUTPUT_STREAM_last_V_1_vld_in = 1'b1;
    end else begin
        OUTPUT_STREAM_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_648 == 1'd0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        OUTPUT_STREAM_strb_V_1_vld_in = 1'b1;
    end else begin
        OUTPUT_STREAM_strb_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_648 == 1'd0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        OUTPUT_STREAM_user_V_1_vld_in = 1'b1;
    end else begin
        OUTPUT_STREAM_user_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        a_address0 = tmp_13_fu_438_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_address0 = tmp_2_fu_354_p1;
    end else begin
        a_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        a_ce0 = 1'b1;
    end else begin
        a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond3_i_reg_531 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_we0 = 1'b1;
    end else begin
        a_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond3_i_fu_342_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond2_i_fu_359_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond1_i_fu_376_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state11 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state11 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_i_fu_490_p2 == 1'd1)) begin
        ap_condition_pp3_exit_iter0_state21 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter0_state21 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == OUTPUT_STREAM_dest_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_id_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_last_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_user_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_strb_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_keep_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_data_V_1_ack_in)) & (1'b1 == ap_CS_fsm_state24))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter2 == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond2_i_reg_540 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_i1_0_i_phi_fu_271_p4 = i_1_reg_544;
    end else begin
        ap_phi_mux_i1_0_i_phi_fu_271_p4 = i1_0_i_reg_267;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (exitcond1_i_reg_549 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_i2_0_i_phi_fu_283_p4 = i_2_reg_553;
    end else begin
        ap_phi_mux_i2_0_i_phi_fu_283_p4 = i2_0_i_reg_279;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond3_i_reg_531 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_i_0_i_phi_fu_259_p4 = i_reg_535;
    end else begin
        ap_phi_mux_i_0_i_phi_fu_259_p4 = i_0_i_reg_255;
    end
end

always @ (*) begin
    if ((~((1'b0 == OUTPUT_STREAM_dest_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_id_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_last_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_user_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_strb_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_keep_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_data_V_1_ack_in)) & (1'b1 == ap_CS_fsm_state24))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        b_address0 = tmp_20_fu_472_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        b_address0 = tmp_6_fu_371_p1;
    end else begin
        b_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        b_ce0 = 1'b1;
    end else begin
        b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond2_i_reg_540 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        b_we0 = 1'b1;
    end else begin
        b_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        c_address0 = tmp_18_fu_477_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        c_address0 = tmp_s_fu_388_p1;
    end else begin
        c_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | ((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        c_ce0 = 1'b1;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_i_reg_549 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        c_we0 = 1'b1;
    end else begin
        c_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1))) begin
        out_address0 = tmp_15_fu_502_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        out_address0 = tmp_18_reg_623;
    end else begin
        out_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)))) begin
        out_ce0 = 1'b1;
    end else begin
        out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        out_we0 = 1'b1;
    end else begin
        out_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == INPUT_STREAM_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((exitcond3_i_fu_342_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((exitcond3_i_fu_342_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((exitcond2_i_fu_359_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((exitcond2_i_fu_359_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((exitcond1_i_fu_376_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((exitcond1_i_fu_376_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((tmp_3_fu_397_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((tmp_10_fu_422_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((tmp_16_fu_451_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if ((~((ap_enable_reg_pp3_iter1 == 1'b0) & (exitcond_i_fu_490_p2 == 1'd1) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone)) & ~((ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if ((((ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone)) | ((ap_enable_reg_pp3_iter1 == 1'b0) & (exitcond_i_fu_490_p2 == 1'd1) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state24 : begin
            if ((~((1'b0 == OUTPUT_STREAM_dest_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_id_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_last_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_user_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_strb_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_keep_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_data_V_1_ack_in)) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign INPUT_STREAM_TREADY = INPUT_STREAM_dest_V_0_state[1'd1];

assign INPUT_STREAM_data_V_0_ack_in = INPUT_STREAM_data_V_0_state[1'd1];

assign INPUT_STREAM_data_V_0_load_A = (~INPUT_STREAM_data_V_0_sel_wr & INPUT_STREAM_data_V_0_state_cmp_full);

assign INPUT_STREAM_data_V_0_load_B = (INPUT_STREAM_data_V_0_state_cmp_full & INPUT_STREAM_data_V_0_sel_wr);

assign INPUT_STREAM_data_V_0_sel = INPUT_STREAM_data_V_0_sel_rd;

assign INPUT_STREAM_data_V_0_state_cmp_full = ((INPUT_STREAM_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign INPUT_STREAM_data_V_0_vld_in = INPUT_STREAM_TVALID;

assign INPUT_STREAM_data_V_0_vld_out = INPUT_STREAM_data_V_0_state[1'd0];

assign INPUT_STREAM_dest_V_0_vld_in = INPUT_STREAM_TVALID;

assign OUTPUT_STREAM_TDATA = OUTPUT_STREAM_data_V_1_data_out;

assign OUTPUT_STREAM_TDEST = OUTPUT_STREAM_dest_V_1_data_out;

assign OUTPUT_STREAM_TID = OUTPUT_STREAM_id_V_1_data_out;

assign OUTPUT_STREAM_TKEEP = OUTPUT_STREAM_keep_V_1_data_out;

assign OUTPUT_STREAM_TLAST = OUTPUT_STREAM_last_V_1_data_out;

assign OUTPUT_STREAM_TSTRB = OUTPUT_STREAM_strb_V_1_data_out;

assign OUTPUT_STREAM_TUSER = OUTPUT_STREAM_user_V_1_data_out;

assign OUTPUT_STREAM_TVALID = OUTPUT_STREAM_dest_V_1_state[1'd0];

assign OUTPUT_STREAM_data_V_1_ack_in = OUTPUT_STREAM_data_V_1_state[1'd1];

assign OUTPUT_STREAM_data_V_1_ack_out = OUTPUT_STREAM_TREADY;

assign OUTPUT_STREAM_data_V_1_load_A = (~OUTPUT_STREAM_data_V_1_sel_wr & OUTPUT_STREAM_data_V_1_state_cmp_full);

assign OUTPUT_STREAM_data_V_1_load_B = (OUTPUT_STREAM_data_V_1_state_cmp_full & OUTPUT_STREAM_data_V_1_sel_wr);

assign OUTPUT_STREAM_data_V_1_sel = OUTPUT_STREAM_data_V_1_sel_rd;

assign OUTPUT_STREAM_data_V_1_state_cmp_full = ((OUTPUT_STREAM_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign OUTPUT_STREAM_data_V_1_vld_out = OUTPUT_STREAM_data_V_1_state[1'd0];

assign OUTPUT_STREAM_dest_V_1_ack_in = OUTPUT_STREAM_dest_V_1_state[1'd1];

assign OUTPUT_STREAM_dest_V_1_ack_out = OUTPUT_STREAM_TREADY;

assign OUTPUT_STREAM_dest_V_1_data_out = 5'd0;

assign OUTPUT_STREAM_dest_V_1_sel = OUTPUT_STREAM_dest_V_1_sel_rd;

assign OUTPUT_STREAM_dest_V_1_vld_out = OUTPUT_STREAM_dest_V_1_state[1'd0];

assign OUTPUT_STREAM_id_V_1_ack_in = OUTPUT_STREAM_id_V_1_state[1'd1];

assign OUTPUT_STREAM_id_V_1_ack_out = OUTPUT_STREAM_TREADY;

assign OUTPUT_STREAM_id_V_1_data_out = 5'd0;

assign OUTPUT_STREAM_id_V_1_sel = OUTPUT_STREAM_id_V_1_sel_rd;

assign OUTPUT_STREAM_id_V_1_vld_out = OUTPUT_STREAM_id_V_1_state[1'd0];

assign OUTPUT_STREAM_keep_V_1_ack_in = OUTPUT_STREAM_keep_V_1_state[1'd1];

assign OUTPUT_STREAM_keep_V_1_ack_out = OUTPUT_STREAM_TREADY;

assign OUTPUT_STREAM_keep_V_1_data_out = 4'd15;

assign OUTPUT_STREAM_keep_V_1_sel = OUTPUT_STREAM_keep_V_1_sel_rd;

assign OUTPUT_STREAM_keep_V_1_vld_out = OUTPUT_STREAM_keep_V_1_state[1'd0];

assign OUTPUT_STREAM_last_V_1_ack_in = OUTPUT_STREAM_last_V_1_state[1'd1];

assign OUTPUT_STREAM_last_V_1_ack_out = OUTPUT_STREAM_TREADY;

assign OUTPUT_STREAM_last_V_1_load_A = (~OUTPUT_STREAM_last_V_1_sel_wr & OUTPUT_STREAM_last_V_1_state_cmp_full);

assign OUTPUT_STREAM_last_V_1_load_B = (OUTPUT_STREAM_last_V_1_state_cmp_full & OUTPUT_STREAM_last_V_1_sel_wr);

assign OUTPUT_STREAM_last_V_1_sel = OUTPUT_STREAM_last_V_1_sel_rd;

assign OUTPUT_STREAM_last_V_1_state_cmp_full = ((OUTPUT_STREAM_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign OUTPUT_STREAM_last_V_1_vld_out = OUTPUT_STREAM_last_V_1_state[1'd0];

assign OUTPUT_STREAM_strb_V_1_ack_in = OUTPUT_STREAM_strb_V_1_state[1'd1];

assign OUTPUT_STREAM_strb_V_1_ack_out = OUTPUT_STREAM_TREADY;

assign OUTPUT_STREAM_strb_V_1_data_out = 4'd15;

assign OUTPUT_STREAM_strb_V_1_sel = OUTPUT_STREAM_strb_V_1_sel_rd;

assign OUTPUT_STREAM_strb_V_1_vld_out = OUTPUT_STREAM_strb_V_1_state[1'd0];

assign OUTPUT_STREAM_user_V_1_ack_in = OUTPUT_STREAM_user_V_1_state[1'd1];

assign OUTPUT_STREAM_user_V_1_ack_out = OUTPUT_STREAM_TREADY;

assign OUTPUT_STREAM_user_V_1_data_out = 4'd0;

assign OUTPUT_STREAM_user_V_1_sel = OUTPUT_STREAM_user_V_1_sel_rd;

assign OUTPUT_STREAM_user_V_1_vld_out = OUTPUT_STREAM_user_V_1_state[1'd0];

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((exitcond3_i_reg_531 == 1'd0) & (1'b0 == INPUT_STREAM_data_V_0_vld_out) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((exitcond3_i_reg_531 == 1'd0) & (1'b0 == INPUT_STREAM_data_V_0_vld_out) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((exitcond2_i_reg_540 == 1'd0) & (1'b0 == INPUT_STREAM_data_V_0_vld_out) & (ap_enable_reg_pp1_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((exitcond2_i_reg_540 == 1'd0) & (1'b0 == INPUT_STREAM_data_V_0_vld_out) & (ap_enable_reg_pp1_iter1 == 1'b1));
end

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((exitcond1_i_reg_549 == 1'd0) & (1'b0 == INPUT_STREAM_data_V_0_vld_out) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((exitcond1_i_reg_549 == 1'd0) & (1'b0 == INPUT_STREAM_data_V_0_vld_out) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp3_stage0_11001 = (((1'b1 == ap_block_state23_io) & (ap_enable_reg_pp3_iter2 == 1'b1)) | ((1'b1 == ap_block_state22_io) & (ap_enable_reg_pp3_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp3_stage0_subdone = (((1'b1 == ap_block_state23_io) & (ap_enable_reg_pp3_iter2 == 1'b1)) | ((1'b1 == ap_block_state22_io) & (ap_enable_reg_pp3_iter1 == 1'b1)));
end

assign ap_block_state11_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp2_stage0_iter1 = ((exitcond1_i_reg_549 == 1'd0) & (1'b0 == INPUT_STREAM_data_V_0_vld_out));
end

assign ap_block_state21_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state22_io = ((exitcond_i_reg_648 == 1'd0) & (1'b0 == OUTPUT_STREAM_data_V_1_ack_in));
end

assign ap_block_state22_pp3_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state23_io = ((ap_reg_pp3_iter1_exitcond_i_reg_648 == 1'd0) & (1'b0 == OUTPUT_STREAM_data_V_1_ack_in));
end

assign ap_block_state23_pp3_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state24 = ((1'b0 == OUTPUT_STREAM_dest_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_id_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_last_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_user_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_strb_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_keep_V_1_ack_in) | (1'b0 == OUTPUT_STREAM_data_V_1_ack_in));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter1 = ((exitcond3_i_reg_531 == 1'd0) & (1'b0 == INPUT_STREAM_data_V_0_vld_out));
end

assign ap_block_state8_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp1_stage0_iter1 = ((exitcond2_i_reg_540 == 1'd0) & (1'b0 == INPUT_STREAM_data_V_0_vld_out));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign exitcond1_i_fu_376_p2 = ((ap_phi_mux_i2_0_i_phi_fu_283_p4 == 15'd25000) ? 1'b1 : 1'b0);

assign exitcond2_i_fu_359_p2 = ((ap_phi_mux_i1_0_i_phi_fu_271_p4 == 14'd13500) ? 1'b1 : 1'b0);

assign exitcond3_i_fu_342_p2 = ((ap_phi_mux_i_0_i_phi_fu_259_p4 == 11'd1350) ? 1'b1 : 1'b0);

assign exitcond_i_fu_490_p2 = ((i3_0_i_reg_324 == 15'd25000) ? 1'b1 : 1'b0);

assign i_0_i_i_cast_fu_393_p1 = i_0_i_i_reg_291;

assign i_1_fu_365_p2 = (ap_phi_mux_i1_0_i_phi_fu_271_p4 + 14'd1);

assign i_2_fu_382_p2 = (ap_phi_mux_i2_0_i_phi_fu_283_p4 + 15'd1);

assign i_3_fu_402_p2 = (i_0_i_i_reg_291 + 31'd1);

assign i_4_fu_496_p2 = (i3_0_i_reg_324 + 15'd1);

assign i_fu_348_p2 = (ap_phi_mux_i_0_i_phi_fu_259_p4 + 11'd1);

assign j_0_i_i_cast_fu_447_p1 = j_0_i_i_reg_313;

assign j_fu_456_p2 = (j_0_i_i_reg_313 + 31'd1);

assign k_0_i_i_cast_fu_418_p1 = k_0_i_i_reg_302;

assign k_fu_427_p2 = (k_0_i_i_reg_302 + 31'd1);

assign last_assign_fu_507_p2 = ((i3_0_i_reg_324 == 15'd24999) ? 1'b1 : 1'b0);

assign out_d0 = (c_load_reg_638 + tmp_21_reg_643);

assign tmp_10_fu_422_p2 = (($signed(k_0_i_i_cast_fu_418_p1) < $signed(K_reg_525)) ? 1'b1 : 1'b0);

assign tmp_12_fu_433_p2 = (k_0_i_i_cast_fu_418_p1 + tmp_7_reg_567);

assign tmp_13_fu_438_p1 = $signed(tmp_12_fu_433_p2);

assign tmp_14_fu_443_p1 = k_0_i_i_cast_reg_577;

assign tmp_14_fu_443_p2 = ($signed(N_reg_518) * $signed({{1'b0}, {tmp_14_fu_443_p1}}));

assign tmp_15_fu_502_p1 = i3_0_i_reg_324;

assign tmp_16_fu_451_p2 = (($signed(j_0_i_i_cast_fu_447_p1) < $signed(N_reg_518)) ? 1'b1 : 1'b0);

assign tmp_17_fu_462_p2 = (j_0_i_i_cast_fu_447_p1 + tmp_9_reg_572);

assign tmp_18_fu_477_p1 = $signed(tmp_17_reg_613);

assign tmp_19_fu_467_p2 = (j_0_i_i_cast_fu_447_p1 + tmp_14_reg_600);

assign tmp_20_fu_472_p1 = $signed(tmp_19_fu_467_p2);

assign tmp_21_fu_481_p2 = ($signed(b_load_reg_633) * $signed(A_PART_reg_595));

assign tmp_2_fu_354_p1 = i_0_i_reg_255;

assign tmp_3_fu_397_p2 = (($signed(i_0_i_i_cast_fu_393_p1) < $signed(M_reg_513)) ? 1'b1 : 1'b0);

assign tmp_6_fu_371_p1 = i1_0_i_reg_267;

assign tmp_7_fu_408_p1 = i_0_i_i_cast_fu_393_p1;

assign tmp_7_fu_408_p2 = ($signed(K_reg_525) * $signed({{1'b0}, {tmp_7_fu_408_p1}}));

assign tmp_9_fu_413_p1 = i_0_i_i_cast_fu_393_p1;

assign tmp_9_fu_413_p2 = ($signed(N_reg_518) * $signed({{1'b0}, {tmp_9_fu_413_p1}}));

assign tmp_s_fu_388_p1 = i2_0_i_reg_279;

always @ (posedge ap_clk) begin
    k_0_i_i_cast_reg_577[31] <= 1'b0;
end

endmodule //HLS_accel
